<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Listeners Test Suite" duration-ms="90" started-at="2017-09-06T00:12:50Z" finished-at="2017-09-06T00:12:50Z">
    <groups>
    </groups>
    <test name="Application Test 1" duration-ms="33" started-at="2017-09-06T00:12:50Z" finished-at="2017-09-06T00:12:50Z">
      <class name="testClasses.TestNG_ListenerTest1">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testClasses.TestNG_ListenerTest1@1ee9faa]" name="beforeClass" is-config="true" duration-ms="8" started-at="2017-09-05T17:12:50Z" finished-at="2017-09-05T17:12:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="testMethod1()[pri:0, instance:testClasses.TestNG_ListenerTest1@1ee9faa]" name="testMethod1" duration-ms="7" started-at="2017-09-05T17:12:50Z" finished-at="2017-09-05T17:12:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="FAIL" signature="testMethod2()[pri:0, instance:testClasses.TestNG_ListenerTest1@1ee9faa]" name="testMethod2" duration-ms="1" started-at="2017-09-05T17:12:50Z" finished-at="2017-09-05T17:12:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at testClasses.TestNG_ListenerTest1.testMethod2(TestNG_ListenerTest1.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testClasses.TestNG_ListenerTest1@1ee9faa]" name="afterTest" is-config="true" duration-ms="1" started-at="2017-09-05T17:12:50Z" finished-at="2017-09-05T17:12:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testClasses.TestNG_ListenerTest1 -->
    </test> <!-- Application Test 1 -->
    <test name="Application Test 2" duration-ms="9" started-at="2017-09-06T00:12:50Z" finished-at="2017-09-06T00:12:50Z">
      <class name="testClasses.TestNG_ListenerTest2">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testClasses.TestNG_ListenerTest2@a3ffec]" name="beforeClass" is-config="true" duration-ms="1" started-at="2017-09-05T17:12:50Z" finished-at="2017-09-05T17:12:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="testMethod1()[pri:0, instance:testClasses.TestNG_ListenerTest2@a3ffec]" name="testMethod1" duration-ms="1" started-at="2017-09-05T17:12:50Z" finished-at="2017-09-05T17:12:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="FAIL" signature="testMethod2()[pri:0, instance:testClasses.TestNG_ListenerTest2@a3ffec]" name="testMethod2" duration-ms="1" started-at="2017-09-05T17:12:50Z" finished-at="2017-09-05T17:12:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at testClasses.TestNG_ListenerTest2.testMethod2(TestNG_ListenerTest2.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testClasses.TestNG_ListenerTest2@a3ffec]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-09-05T17:12:50Z" finished-at="2017-09-05T17:12:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testClasses.TestNG_ListenerTest2 -->
    </test> <!-- Application Test 2 -->
  </suite> <!-- Listeners Test Suite -->
</testng-results>
